# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('day1', models.CharField(max_length=5)),
                ('day2', models.CharField(max_length=5)),
                ('day3', models.CharField(max_length=5)),
                ('day4', models.CharField(max_length=5)),
                ('day5', models.CharField(max_length=5)),
                ('day6', models.CharField(max_length=5)),
                ('day7', models.CharField(max_length=5)),
                ('day8', models.CharField(max_length=5)),
                ('day9', models.CharField(max_length=5)),
                ('day10', models.CharField(max_length=5)),
                ('day11', models.CharField(max_length=5)),
                ('day12', models.CharField(max_length=5)),
                ('day13', models.CharField(max_length=5)),
                ('day14', models.CharField(max_length=5)),
                ('day15', models.CharField(max_length=5)),
                ('day16', models.CharField(max_length=5)),
                ('day17', models.CharField(max_length=5)),
                ('day18', models.CharField(max_length=5)),
                ('day19', models.CharField(max_length=5)),
                ('day20', models.CharField(max_length=5)),
                ('day21', models.CharField(max_length=5)),
                ('day22', models.CharField(max_length=5)),
                ('day23', models.CharField(max_length=5)),
                ('day24', models.CharField(max_length=5)),
                ('day25', models.CharField(max_length=5)),
                ('day26', models.CharField(max_length=5)),
                ('day27', models.CharField(max_length=5)),
                ('day28', models.CharField(max_length=5)),
                ('day29', models.CharField(max_length=5)),
                ('day30', models.CharField(max_length=5)),
                ('day31', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(choices=[('Dir', 'Director'), ('D', 'Developer'), ('HR', 'Manager'), ('P', 'Peon'), ('SG', 'Security Guard'), ('SW', 'Sweeper')], max_length=50)),
                ('work_profile', models.CharField(choices=[('C++', 'C++'), ('PHP', 'PHP'), ('JAVA', 'Core Java'), ('C#', 'C#'), ('PY', 'Python'), ('Non', 'None')], max_length=50)),
                ('salary', models.IntegerField(default=10)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
